### ISSUE TITLE
--go option bug or documentation issue

### ISSUE THREAD

**Issue by mortenjc** [ess-dmsc/kafkacow#114]
I just tested the -g option and got a confusing warning/error

```
./bin/kafkacow -C -b localhost:9092 -t FREIA_detector -d 2020-04-28T00:00:00.0 -g 6:8
--go: Value 6:8 not in range 0 to 9223372036854775807
```
Clearly 6 and 8 are both in the range 0 to (very big number)

**Comment by matthew-d-jones** [comment]
I guess the documentation is not clear.
`-g` should be a single integer: the number of messages you want from the given offset or datetime

**Comment by mortenjc** [comment]
Hah, ok I misunderstood that one.

**Comment by mortenjc** [comment]
Not important
