### ISSUE TITLE
Bug when specifying future datetime?

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/kafkacow#115]
Reported by Morten Christensen. Requires some investigation:

```
./bin/kafkacow -C -b localhost:9092 -t FREIA_detector -d 2022-05-28T00:00:00.0
```

note the year
This is the output:
```
Mon 27-Apr-2020 07:20:25.0  ||  2020-04-27T07:20:25.0                                  ||

Timestamp: 1587972025000 || PartitionID:     0 || Offset:       0 || File Identifier: ev42 ||
{
    detector_id: [
        719
```

**Comment by mortenjc** [comment]
I am not convinced this is a bug. It could also be the case that I had a weird kafka log containing timestamps that were not in chronological order. Will probably need to test this on a fresh log.

**Comment by matthew-d-jones** [comment]
I've not managed to reproduce this. Closing ticket, can be reopened if observed again.
