### ISSUE TITLE
-a does not work

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/kafkacow#29]
`-a` doesn't currently print anything, all i see is `[2018-09-24 09:18:22.610] [LOG] [info] Welcome to spdlog!`

Maybe as the `-L` option exists, `-a` doesn't need to exist anymore

**Comment by mchorazak** [comment]
`-a` is meant to be used in `-L` mode, for example
`-b hinata.isis.cclrc.ac.uk:9092 -L -a` gives a simple list of topics
and
`-b hinata.isis.cclrc.ac.uk:9092 -L` gives a detailed list of brokers, topics, partitions etc.
